name: wasm-simd-hf-space-en-asr-zipformer

on:
  workflow_dispatch:

concurrency:
  group: wasm-simd-hf-space-en-asr-zipformer-${{ github.ref }}
  cancel-in-progress: true

jobs:
  wasm-simd-hf-space-en-asr-zipformer:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

#      - name: Capture file access times BEFORE run
#        shell: bash
#        run: |
#          ./get-file-access-times-before.sh

      - name: Install emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.51
          actions-cache-folder: 'emsdk-cache'

      - name: View emsdk version
        shell: bash
        run: |
          emcc -v
          echo "--------------------"
          emcc --check

      - name: Download model files
        shell: bash
        run: |
          cd wasm/asr/assets
          ls -lh
          echo "----------"

          wget -q https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-streaming-zipformer-en-2023-06-21.tar.bz2
          tar xvf sherpa-onnx-streaming-zipformer-en-2023-06-21.tar.bz2
          rm sherpa-onnx-streaming-zipformer-en-2023-06-21.tar.bz2
          mv sherpa-onnx-streaming-zipformer-en-2023-06-21/encoder-epoch-99-avg-1.int8.onnx encoder.onnx
          mv sherpa-onnx-streaming-zipformer-en-2023-06-21/decoder-epoch-99-avg-1.onnx decoder.onnx
          mv sherpa-onnx-streaming-zipformer-en-2023-06-21/joiner-epoch-99-avg-1.onnx joiner.onnx
          mv sherpa-onnx-streaming-zipformer-en-2023-06-21/tokens.txt ./

          rm -rf sherpa-onnx-streaming-zipformer-en-2023-06-21

          ls -lh

      - name: Build sherpa-onnx for WebAssembly (ASR)
        shell: bash
        run: |
          .github/scripts/build-wasm-simd-asr.sh

#      - name: Capture file access times AFTER run
#        shell: bash
#        run: |
#          ./get-file-access-times-after.sh
#      - name: Archive results
#        uses: actions/upload-artifact@v4
#        with:
#          name: Work folder
#          path: WORK/

      - name: collect files
        shell: bash
        run: |
          SHERPA_ONNX_VERSION=v$(grep "SHERPA_ONNX_VERSION" ./CMakeLists.txt  | cut -d " " -f 2  | cut -d '"' -f 2)

          dst=sherpa-onnx-wasm-simd-${SHERPA_ONNX_VERSION}-en-asr-zipformer
          mv build-wasm-simd-asr/install/bin/wasm/asr $dst
          ls -lh $dst
          tar cjfv ${dst}.tar.bz2 ./${dst}

      - name: Upload wasm files
        uses: actions/upload-artifact@v4
        with:
          name: sherpa-onnx-wasm-simd-en-asr-zipformer
          path: ./sherpa-onnx-wasm-simd-*.tar.bz2
